Development branch for home and about page for Capstone Project
CobbyElsonfx/Code-Future pull request #5
Opened 2023-07-01 19:27 UTC by CobbyElsonfx

# Capstone Project
## #  [Link to  Project Instructions](https://github.com/microverseinc/curriculum-html-css/blob/main/capstone/html_capstone.md)
## In this PR I implemented  and ensured the following:

### - [ ] Built the home page and about page for both mobile and desktop  and ensured that

- The home page  has a link in the menu to the about page.
- The logo in the header links to the home page.
- When the user clicks (or taps) the hamburger button on the header, the mobile menu appears over the page.
- The mobile menu should has a close (X) button that closes the menu.
- The section "Featured speakers" should be created dynamically in JavaScript.
- Rendered featured speakers on page load using js events

2023-07-01 20:19 UTC, skyv26 requested changes
## Hi @CobbyElsonfx, 

Good job so far 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

## STATUS: REQUIRE CHANGES 🔴 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNDYxMmUyNzBhYzk4ZGVhZDYxM2M2NGRlMjBjYzU4MmY1ODU2ZWY5NiZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PXM/B7v6pJ6rQORbxcggN5/giphy.gif)

## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implement the features ✅ 
- Nice *UI* design ✅ 
- Professional `README` template ✅ 
- Linters are green ✅ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

#### Cheers, and Happy coding!👏👏👏

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-01 20:19 UTC, skyv26 commented on css/style.css
- [ ] Kindly adhere to the project requirement because as I can see your footer design for both **index.html** and **about.html** is not matching with the original design and needs some adjustments, your design is `inconsistent` and looks unprofessional. I am not able to make the `inline comments`  at the specific lines because the code is not visible in the github feature so that's why I am making the comments on the file, but below after having a look at the below-attached image and table Please see the commented code to understand where exactly changes are required.

### Requirement
![image](https://user-images.githubusercontent.com/66476329/236188683-4224cc77-237d-413d-9942-91297c87687b.png)

### Design Comparison
<table>
<tr>
<th>Cindy Shin's Design</th>
<th>Your Design</th>
</tr>
<tr>
<td>

![image](https://github.com/CobbyElsonfx/Code-Future/assets/66476329/93c5cdcf-47cd-4f42-a46e-cbbd2bee674f)

</td>
<td>

![Screenshot from 2023-07-02 01-04-13](https://github.com/CobbyElsonfx/Code-Future/assets/66476329/21540405-7c0e-440b-b001-06c7395877d6)

</td>
</tr>
</table>

#### Line no 408  
```css
  footer {
    height: 245px;
    background-color: var(--primary);
    display: flex;
    align-items: center;
  }
```

2023-07-01 20:19 UTC, skyv26 commented on css/style.css
- [ ] Kindly adhere to the project requirement because as I can see your design is not matching with the original design and needs some adjustments, your design is `inconsistent` and looks unprofessional. I am not able to make the `inline comments`  at the specific lines because the code is not visible in the github feature so that's why I am making the comments on the file. but below after having a look at the below-attached image and table please see the commented code to understand where exactly changes are required. Your **feature-section** needs space as per the Behance design.

### Requirement
![image](https://user-images.githubusercontent.com/66476329/236188683-4224cc77-237d-413d-9942-91297c87687b.png)

### Design Comparison
<table>
<tr>
<th>Cindy Shin's Design</th>
<th>Your Design</th>
</tr>
<tr>
<td>

![image](https://github.com/CobbyElsonfx/Code-Future/assets/66476329/f4ed5fed-bd68-4359-ac6c-b6b29ddffaf6)

</td>
<td>

![Screenshot from 2023-07-02 01-04-27](https://github.com/CobbyElsonfx/Code-Future/assets/66476329/490696d1-3489-4835-9d0b-a2665f0fceb6)

</td>
</tr>
</table>

#### Line no 318  and please use the correct color for the underline of the text or title.
```css
  .pioneers-container .featured-speakers-header-title {
    color: #000;
    font-size: 30px;
    line-height: 23px;
    letter-spacing: -0.3px;
  }
```

2023-07-01 20:19 UTC, skyv26 commented on css/style.css
- [ ] Kindly adhere to the project requirement because as I can see your `Speaker` section is not matching with the original design and needs some adjustments, your design is `inconsistent` and looks unprofessional. I am not able to make the `inline comments`  at the specific lines because the code is not visible in the github feature so that's why I am making the comments on the file. but below after having a look at the below-attached image and table please see the commented code to understand where exactly changes are required. I have also attached a video within this comment to see how your speaker section content looks bad on different screen sizes. Kindly make it a fully responsive design.

### Requirement
![image](https://user-images.githubusercontent.com/66476329/236188683-4224cc77-237d-413d-9942-91297c87687b.png)

### Design Comparison
<table>
<tr>
<th>Cindy Shin's Design</th>
<th>Your Design</th>
</tr>
<tr>
<td>

![image](https://github.com/CobbyElsonfx/Code-Future/assets/66476329/f4ed5fed-bd68-4359-ac6c-b6b29ddffaf6)

</td>
<td>

![Screenshot from 2023-07-02 01-04-27](https://github.com/CobbyElsonfx/Code-Future/assets/66476329/490696d1-3489-4835-9d0b-a2665f0fceb6)

</td>
</tr>
</table>

#### Line no 318  and please use the correct color.
```css
  #pioneers-row {
    width: 100%;
    display: flex;
    justify-content: center;
    align-items: center;
    gap: 25px;
  }
```


### Video 🎥 

[Screencast from 02-07-23 01:05:55 AM IST.webm](https://github.com/CobbyElsonfx/Code-Future/assets/66476329/f8b529ed-b2b9-4ee4-9b4a-1475cbe92dc3)

2023-07-01 20:19 UTC, skyv26 commented on index.html
- [ ] Kindly use **h3** instead of **h2** because it optimizes the main heading of your portfolio website and enhances the user experience. The `h2` tag is specifically designed for secondary headings, providing a clear and prominent representation of the page's primary topic or purpose. By utilizing the *h3* tag, you create a visual hierarchy that helps users quickly identify and determine the relevance of the content to their needs and interests. This improves the overall usability and navigation of your website, ensuring a more engaging and effective experience for visitors.

```html
<h2>
              2023.10.15(THU) ~ 16(FRI)
            </h2>
```

2023-07-01 20:19 UTC, skyv26 commented on index.html
- [ ] Kindly use **h3** instead of **h2** because it optimizes the main heading of your portfolio website and enhances the user experience. The `h2` tag is specifically designed for secondary headings, providing a clear and prominent representation of the page's primary topic or purpose. By utilizing the *h3* tag, you create a visual hierarchy that helps users quickly identify and determine the relevance of the content to their needs and interests. This improves the overall usability and navigation of your website, ensuring a more engaging and effective experience for visitors.

```HTML
<h2 class="card-header">Main Programs</h2>
```

- Please do this changes for all sections heading.

2023-07-01 20:19 UTC, skyv26 commented on index.html
- [ ] Kindly use **h4** instead of **h2** because it optimizes the main heading of your portfolio website and enhances the user experience. The `h2` tag is specifically designed for secondary headings, providing a clear and prominent representation of the page's primary topic or purpose. By utilizing the *h4* tag, you create a visual hierarchy that helps users quickly identify and determine the relevance of the content to their needs and interests. This improves the overall usability and navigation of your website, ensuring a more engaging and effective experience for visitors.

```HTML
<h2 class="card-title">Debate</h2> 
<h2 class="card-title">Awards</h2> 
```

- Please make changes in the `main program` section as I mentioned for all the program cards.

2023-07-01 20:19 UTC, skyv26 commented on css/style.css
- [ ] Please use the `media` query wisely because as I can see that you are using the media query not in a recommended way and because of it your style have some issue at a specific breakpoint that's is 768px, which is a cause of bad user experience. Kindly fix the design issue.

### Screenshot of 768px screen size

![image](https://github.com/CobbyElsonfx/Code-Future/assets/66476329/e28e136b-5403-4457-8458-6ecfac99916f)

2023-07-01 20:19 UTC, skyv26 commented on README.md
- [ ] Please adhere 🙏🏻 to the project requirement according to which you must have to add the `creative cloud` logo in your `acknowledgement` section. Because by doing this any developer will agree to use your project or even you will use the design for just learning purposes not for any commercial purpose.
![image](https://github.com/CobbyElsonfx/Code-Future/assets/66476329/b740915a-a30b-4985-bdcb-02e9ad769d3e)

2023-07-01 22:49 UTC, CobbyElsonfx commented on README.md
@skyv26  I implemented all changes except this of which I do  not understand , Please can you explain what you mean by creative cloud logo

2023-07-01 23:22 UTC, Munsa1 approved these changes
Hi @CobbyElsonfx, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
Passing Linters :heavy_check_mark: 
Correct GitHub Flow :heavy_check_mark: 
Descriptive ReadMe File :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-01 23:27 UTC, merged

2023-07-02 04:26 UTC, skyv26 commented on README.md
@CobbyElsonfx Please you can find creative cloud logo from the behance website easily

2023-07-02 12:02 UTC, CobbyElsonfx commented on README.md
Thanks very much Sir, I really appreciate your help.